---

- name: Add PostgreSQL Repository
  become: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' state=present

- name: Add Keys for PostgreSQL Repository
  become: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Update apt
  become: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Install PostgreSQL Packages
  become: yes
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - postgresql
    - postgresql-client
    - python-pygresql
    - python-psycopg2

- name: Create databases
  become: yes
  become_user: postgres
  postgresql_db: name={{ postgresql.database }} state=present

- name: Import dump
  become: yes
  become_user: postgres
  shell: psql {{ postgresql.database }} < /vagrant/{{ postgresql.dump }}
  when: postgresql.dump

- name: Create users
  become: yes
  become_user: postgres
  postgresql_user: name={{ postgresql.user }} password={{ postgresql.password }} db={{ postgresql.database }} priv=ALL encrypted=true
